[project]
name = "agenda-citas-app"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.10"
authors = [
    { name = "Luis Diaz", email = "you@example.com" }
]
dependencies = [
    "flet>=0.86.5"
]

[dependency-groups]
dev = [
    "flet-cli>=0.86.5",
    "flet-desktop>=0.86.5",
    "flet-web>=0.86.5",
]

[tool.flet]
org = "com.luisdiaz"
product = "agenda-citas-app"
company = "Luis Diaz"
copyright = "Copyright (C) 2026 Luis Diaz"
